Data Manipulation and Analysis with pandas
Data manipulation and analysis are key tasks in any data science or data anaylisis project. Pandas provides a wide range of functions for data manipulation and anaylysis , making it easier to clean ,transform , and extract insight from data. in

In [2]:
##
import pandas as pd

In [3]:
df = pd.read_csv('Ds_salaries.csv')
## fecth the first 5 row 
df.head(5)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L

In [4]:
df.tail(5)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
14833,2022,MI,FT,Business Intelligence Developer,15000,USD,15000,GH,100,GH,M
14834,2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M
14835,2021,EN,FT,Machine Learning Developer,15000,USD,15000,TH,100,TH,L
14836,2022,EN,FT,Data Analyst,15000,USD,15000,ID,0,ID,L
14837,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S

In [5]:
df.describe()

          work_year        salary  salary_in_usd  remote_ratio
count  14838.000000  1.483800e+04   14838.000000  14838.000000
mean    2023.138900  1.650227e+05  149874.718763     32.760480
std        0.700799  3.562354e+05   69009.181349     46.488278
min     2020.000000  1.400000e+04   15000.000000      0.000000
25%     2023.000000  1.021000e+05  102000.000000      0.000000
50%     2023.000000  1.422000e+05  141300.000000      0.000000
75%     2024.000000  1.875000e+05  185900.000000    100.000000
max     2024.000000  3.040000e+07  800000.000000    100.000000

In [6]:
df.dtypes

work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

In [7]:
## handling missing values
df.isnull()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
14833,False,False,False,False,False,False,False,False,False,False,False
14834,False,False,False,False,False,False,False,False,False,False,False
14835,False,False,False,False,False,False,False,False,False,False,False
14836,False,False,False,False,False,False,False,False,False,False,False
14837,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [9]:
df.fillna(0)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L
...,...,...,...,...,...,...,...,...,...,...,...
14833,2022,MI,FT,Business Intelligence Developer,15000,USD,15000,GH,100,GH,M
14834,2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M
14835,2021,EN,FT,Machine Learning Developer,15000,USD,15000,TH,100,TH,L
14836,2022,EN,FT,Data Analyst,15000,USD,15000,ID,0,ID,L
14837,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S

In [10]:
df_filled = df.fillna(0)

In [11]:
# filling missing values with the mean of the column 
work_year_mean = df['work_year'].mean()
print('mean of work_year:', work_year_mean)
work_year_mean
df['14836'] = df['work_year'].fillna(work_year_mean)
df

mean of work_year: 2023.1389001213101

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,14836
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L,2021
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L,2021
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L,2020
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S,2021
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L,2022
...,...,...,...,...,...,...,...,...,...,...,...,...
14833,2022,MI,FT,Business Intelligence Developer,15000,USD,15000,GH,100,GH,M,2022
14834,2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M,2020
14835,2021,EN,FT,Machine Learning Developer,15000,USD,15000,TH,100,TH,L,2021
14836,2022,EN,FT,Data Analyst,15000,USD,15000,ID,0,ID,L,2022
14837,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S,2020

In [12]:
## renaming columns
df.rename(columns={'work_year': 'year'}, inplace=True)
df

,year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,14836
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L,2021
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L,2021
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L,2020
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S,2021
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L,2022
...,...,...,...,...,...,...,...,...,...,...,...,...
14833,2022,MI,FT,Business Intelligence Developer,15000,USD,15000,GH,100,GH,M,2022
14834,2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M,2020
14835,2021,EN,FT,Machine Learning Developer,15000,USD,15000,TH,100,TH,L,2021
14836,2022,EN,FT,Data Analyst,15000,USD,15000,ID,0,ID,L,2022
14837,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S,2020

In [13]:
df.head()

,year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,14836
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L,2021
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L,2021
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L,2020
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S,2021
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L,2022

In [14]:
## change data type 
df['year'] = df['year'].astype(int)
df.dtypes
## handling duplicates
df.duplicated()
df.drop_duplicates(inplace=True)
df

,year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,14836
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L,2021
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L,2021
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L,2020
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S,2021
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L,2022
...,...,...,...,...,...,...,...,...,...,...,...,...
14833,2022,MI,FT,Business Intelligence Developer,15000,USD,15000,GH,100,GH,M,2022
14834,2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M,2020
14835,2021,EN,FT,Machine Learning Developer,15000,USD,15000,TH,100,TH,L,2021
14836,2022,EN,FT,Data Analyst,15000,USD,15000,ID,0,ID,L,2022
14837,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S,2020

In [15]:
df['New Value ']= df['salary'].apply(lambda x:x*2)
df.head()

,year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,14836,New Value
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L,2021,60800000
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L,2021,22000000
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L,2020,22000000
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S,2021,17000000
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L,2022,15000000

In [16]:
## Data Aggregating and Grouping
# Average and median salary plus employee count per job title
job_salary_summary = (
    df.groupby('job_title')
      .agg(employee_count=('job_title', 'size'),
           avg_salary_usd=('salary_in_usd', 'mean'),
           median_salary_usd=('salary_in_usd', 'median'))
      .reset_index()
      .sort_values('employee_count', ascending=False)
)
job_salary_summary.head(10)

# Salary and remote ratio trends by year and employment type
work_year_summary = (
    df.groupby(['year', 'employment_type'])
      .agg(avg_salary_usd=('salary_in_usd', 'mean'),
           avg_remote_ratio=('remote_ratio', 'mean'))
      .reset_index()
      .sort_values(['year', 'employment_type'])
)
work_year_summary.head(10)

# Pivot table to quickly inspect salary by company size and experience level
salary_pivot = df.pivot_table(
    values='salary_in_usd',
    index='experience_level',
    columns='company_size',
    aggfunc='mean'
)
salary_pivot

# Simple example: get the average salary for each employment_type
avg_salary_by_emp_type = df.groupby('employment_type')['salary_in_usd'].mean()
print(avg_salary_by_emp_type)

employment_type
CT    112007.500000
FL     50236.769231
FT    147220.453813
PT     69608.037037
Name: salary_in_usd, dtype: float64

In [17]:
grouped_sum = df.groupby('salary_in_usd')['year'].sum()
print(grouped_sum)

salary_in_usd
15000      8085
15680      2023
15809      2023
15897      2022
15966      2020
          ...
700000     4046
720000    14168
750000    14164
774000     2024
800000     2024
Name: year, Length: 2730, dtype: int64

In [ ]:
## aggregate multiple  functions 
# Aggregate multiple functions: count, mean, and median salary (in USD) by experience level and company size
agg_multi = (
    df.groupby(['experience_level', 'company_size'])
      .agg(






        ''
          employee_count=('salary_in_usd', 'count'),
          avg_salary_usd=('salary_in_usd', 'mean'),
          median_salary_usd=('salary_in_usd', 'median')
      )
      .reset_index()
      .sort_values(['experience_level', 'company_size'])
)
print(agg_multi.head(10))

  experience_level company_size  employee_count  avg_salary_usd  \
0               EN            L             122    73582.713115
1               EN            M             720    94482.027778
2               EN            S              51    66858.882353
3               EX            L              22   182570.181818
4               EX            M             324   195898.358025
5               EX            S               8   169172.375000
6               MI            L             212   103955.316038
7               MI            M            2188   127051.711152
8               MI            S              66    73522.924242
9               SE            L             268   151392.563433

   median_salary_usd
0            59495.0
1            84000.0
2            56536.0
3           151833.5
4           191928.5
5           147611.0
6            89653.0
7           115000.0
8            61252.0
9           140050.0

In [18]:
df.groupby('experience_level')['salary_in_usd'].mean()

experience_level
EN     90049.220605
EX    194466.076271
MI    123633.489051
SE    163515.717215
Name: salary_in_usd, dtype: float64

In [25]:
## merging and joining dataframes 
# create sample DataFrames 
df1= pd.DataFrame({'key':['A','B','C'],'Value1':[1,2,3]})
df2= pd.DataFrame({'key':['A','B','D'],'Value1':[4,5,6]})

In [ ]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [27]:
df2

  key  Value1
0   A       4
1   B       5
2   D       6

In [30]:
## merege this dataframe on the keycolumns
pd.merge(df1,df2,on='key',how='inner' )

  key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [31]:
pd.merge(df1,df2,on='key',how='outer' )

  key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [32]:
pd.merge(df1,df2,on="key",how="left")

  key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [ ]:
pd.merge(df1,df2,on="key",how="right")

  key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6

In [21]:
import pandas as pd

data = {
    "name": ["Leul", "Sara", "John", "Miki", "Leul"],
    "department": ["IT", "IT", "HR", "HR", "IT"],
    "salary": [5000, 6000, 5500, 6200, 5800]
}

df = pd.DataFrame(data)
print(df)

   name department  salary
0  Leul         IT    5000
1  Sara         IT    6000
2  John         HR    5500
3  Miki         HR    6200
4  Leul         IT    5800

In [22]:
avg_salary = df.groupby("department")["salary"].mean()
print(avg_salary)

department
HR    5850.0
IT    5600.0
Name: salary, dtype: float64

In [23]:
result = df.groupby("department").agg(
    employee_count=("salary", "count"),
    avg_salary=("salary", "mean"),
    max_salary=("salary", "max"),
    min_salary=("salary", "min")
)

print(result)

            employee_count  avg_salary  max_salary  min_salary
department
HR                       2      5850.0        6200        5500
IT                       3      5600.0        6000        5000