Data Manipulation and Analysis with pandas
Data manipulation and analysis are key tasks in any data science or data anaylisis project. Pandas provides a wide range of functions for data manipulation and anaylysis , making it easier to clean ,transform , and extract insight from data. in

In [5]:
##
import pandas as pd

In [6]:
df = pd.read_csv('Ds_salaries.csv')
## fecth the first 5 row 
df.head(5)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L

In [7]:
df.tail(5)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
14833,2022,MI,FT,Business Intelligence Developer,15000,USD,15000,GH,100,GH,M
14834,2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M
14835,2021,EN,FT,Machine Learning Developer,15000,USD,15000,TH,100,TH,L
14836,2022,EN,FT,Data Analyst,15000,USD,15000,ID,0,ID,L
14837,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S

In [8]:
df.describe()

          work_year        salary  salary_in_usd  remote_ratio
count  14838.000000  1.483800e+04   14838.000000  14838.000000
mean    2023.138900  1.650227e+05  149874.718763     32.760480
std        0.700799  3.562354e+05   69009.181349     46.488278
min     2020.000000  1.400000e+04   15000.000000      0.000000
25%     2023.000000  1.021000e+05  102000.000000      0.000000
50%     2023.000000  1.422000e+05  141300.000000      0.000000
75%     2024.000000  1.875000e+05  185900.000000    100.000000
max     2024.000000  3.040000e+07  800000.000000    100.000000

In [9]:
df.dtypes

work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

In [10]:
## handling missing values
df.isnull()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
14833,False,False,False,False,False,False,False,False,False,False,False
14834,False,False,False,False,False,False,False,False,False,False,False
14835,False,False,False,False,False,False,False,False,False,False,False
14836,False,False,False,False,False,False,False,False,False,False,False
14837,False,False,False,False,False,False,False,False,False,False,False

In [11]:
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [12]:
df.fillna(0)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L
...,...,...,...,...,...,...,...,...,...,...,...
14833,2022,MI,FT,Business Intelligence Developer,15000,USD,15000,GH,100,GH,M
14834,2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M
14835,2021,EN,FT,Machine Learning Developer,15000,USD,15000,TH,100,TH,L
14836,2022,EN,FT,Data Analyst,15000,USD,15000,ID,0,ID,L
14837,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S

In [13]:
df_filled = df.fillna(0)

In [19]:
# filling missing values with the mean of the column 
work_year_mean = df['work_year'].mean()
print('mean of work_year:', work_year_mean)
work_year_mean
df['14836'] = df['work_year'].fillna(work_year_mean)
df

mean of work_year: 2023.1389001213101

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,14836
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L,2021
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L,2021
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L,2020
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S,2021
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L,2022
...,...,...,...,...,...,...,...,...,...,...,...,...
14833,2022,MI,FT,Business Intelligence Developer,15000,USD,15000,GH,100,GH,M,2022
14834,2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M,2020
14835,2021,EN,FT,Machine Learning Developer,15000,USD,15000,TH,100,TH,L,2021
14836,2022,EN,FT,Data Analyst,15000,USD,15000,ID,0,ID,L,2022
14837,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S,2020

In [21]:
## renaming columns
df.rename(columns={'work_year': 'year'}, inplace=True)
df

,year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,14836
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L,2021
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L,2021
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L,2020
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S,2021
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L,2022
...,...,...,...,...,...,...,...,...,...,...,...,...
14833,2022,MI,FT,Business Intelligence Developer,15000,USD,15000,GH,100,GH,M,2022
14834,2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M,2020
14835,2021,EN,FT,Machine Learning Developer,15000,USD,15000,TH,100,TH,L,2021
14836,2022,EN,FT,Data Analyst,15000,USD,15000,ID,0,ID,L,2022
14837,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S,2020

In [22]:
df.head()

,year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,14836
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L,2021
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L,2021
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L,2020
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S,2021
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L,2022

In [23]:
## change data type 
df['year'] = df['year'].astype(int)
df.dtypes
## handling duplicates
df.duplicated()
df.drop_duplicates(inplace=True)
df

,year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,14836
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L,2021
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L,2021
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L,2020
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S,2021
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L,2022
...,...,...,...,...,...,...,...,...,...,...,...,...
14833,2022,MI,FT,Business Intelligence Developer,15000,USD,15000,GH,100,GH,M,2022
14834,2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M,2020
14835,2021,EN,FT,Machine Learning Developer,15000,USD,15000,TH,100,TH,L,2021
14836,2022,EN,FT,Data Analyst,15000,USD,15000,ID,0,ID,L,2022
14837,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S,2020